# Generated by Django 5.0.6 on 2024-08-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='airDate',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='animeType',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='demographic',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='description',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='episodeDuration',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='premireSeason',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='prequel',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='sequel',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='titleJpKanj',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='titleJpRoman',
        ),
    ]
