# Generated by Django 5.0.6 on 2024-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_titlejproman_alter_anime_titleenglish'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='titleJpKanj',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
