# Generated by Django 5.0.6 on 2024-10-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_description_anime_titlejpkanj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='titleJpKanj',
            new_name='titleJpKanji',
        ),
    ]
