# Generated by Django 5.0.6 on 2024-10-09 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_anime_prequel_anime_sequel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='prequel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prequel_anime', to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='sequel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequel_anime', to='anime.anime'),
        ),
    ]
