# Generated by Django 5.0.6 on 2024-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_anime_demographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='airDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
