# Generated by Django 5.0.6 on 2024-10-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_rename_aggregate_rating_anime_aggregaterating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='aggregateRating',
            new_name='average_rating',
        ),
    ]
