# Generated by Django 5.0.6 on 2024-10-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_rename_aggregaterating_anime_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='average_rating',
            new_name='aggregateRating',
        ),
    ]
