# Generated by Django 5.0.6 on 2024-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_genre_studio_remove_anime_genre_anime_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genres',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi')], default='Drama', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
