# Generated by Django 5.0.6 on 2024-10-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_remove_anime_genres_anime_genre_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='anime.genre'),
        ),
    ]
