# Generated by Django 5.0.6 on 2024-10-16 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_genre_remove_anime_genre_anime_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='studioName',
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.studio'),
        ),
        migrations.AddField(
            model_name='studio',
            name='establishedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='name',
            field=models.CharField(default='test', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='website',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='demographic',
            field=models.CharField(choices=[('Shonen', 'Shonen'), ('Seinen', 'Seinen'), ('Shojo', 'Shojo'), ('Josei', 'Josei')], max_length=20),
        ),
    ]
