# Generated by Django 5.0.6 on 2024-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0023_anime_image_alter_anime_demographic_alter_anime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titleEnglish',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titleJpRoman',
            field=models.CharField(default='removeMe', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
