# Generated by Django 5.0.6 on 2024-12-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0025_alter_anime_demographic_alter_anime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='total_rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='anime.anime'),
        ),
    ]
