# Generated by Django 5.0.6 on 2024-12-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0026_alter_anime_total_rating_alter_rating_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, to='anime.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titleEnglish',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titleJpKanji',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
