# Generated by Django 5.0.6 on 2024-12-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0027_alter_anime_description_alter_anime_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_images/t'),
        ),
    ]
