# Generated by Django 5.0.6 on 2024-12-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0029_anime_created_by_alter_anime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
