# Generated by Django 5.0.6 on 2024-12-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0031_alter_studio_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.TextField(blank=True, default=''),
        ),
    ]
