# Generated by Django 5.0.6 on 2025-01-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0033_remove_anime_genre_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
