# Generated by Django 5.0.6 on 2024-08-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_airdate_remove_anime_animetype_and_more'),
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='currently_watching',
            field=models.ManyToManyField(blank=True, related_name='currently_watching', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='dropped',
            field=models.ManyToManyField(blank=True, related_name='dropped', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_in',
            field=models.ManyToManyField(blank=True, related_name='interested_in', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_hold',
            field=models.ManyToManyField(blank=True, related_name='on_hold', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_to_watch',
            field=models.ManyToManyField(blank=True, related_name='planned_to_watch', to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
