# Generated by Django 5.0.6 on 2024-12-15 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0026_alter_anime_total_rating_alter_rating_anime'),
        ('user', '0004_user_completed_user_currently_watching_user_dropped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_watched', models.PositiveIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
