# Generated by Django 5.0.6 on 2024-12-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0026_alter_anime_total_rating_alter_rating_anime'),
        ('user', '0006_alter_watchedepisodes_episodes_watched'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedepisodes',
            unique_together={('user', 'anime')},
        ),
    ]
